// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_STNaVlao6ntxx3GynfvFbCAa3ekqNo',
    appId: '1:1008935605582:web:830add9769ee1815c5fa1f',
    messagingSenderId: '1008935605582',
    projectId: 'two-five-app',
    authDomain: 'two-five-app.firebaseapp.com',
    storageBucket: 'two-five-app.appspot.com',
    measurementId: 'G-62DMSEYXW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Ue41g0FdcaqnXghD3utYs1yQvol5Jpw',
    appId: '1:1008935605582:android:3d08b57e0ba7eac3c5fa1f',
    messagingSenderId: '1008935605582',
    projectId: 'two-five-app',
    storageBucket: 'two-five-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQrHbmzIh_a6g1LgXzU3w1hPsdexp2vM',
    appId: '1:1008935605582:ios:c1e8087bd1f469cac5fa1f',
    messagingSenderId: '1008935605582',
    projectId: 'two-five-app',
    storageBucket: 'two-five-app.appspot.com',
    iosBundleId: 'systems.perceptual.twoFive',
  );
}
